################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
xdaq/include/xercesc/util \
xdaq/include/xercesc/framework/psvi \
xdaq/include/xercesc/dom/impl \
TriDAS/emu/web_csc_display/src/common \
TriDAS/emu/supervisor/src/common \
TriDAS/emu/step/test/common \
TriDAS/emu/step/src/common \
TriDAS/emu/soap/src/common \
TriDAS/emu/odmbdev/utils \
TriDAS/emu/odmbdev/src/common \
TriDAS/emu/me11dev/src/common \
TriDAS/emu/fast_daq/daq_common/src \
TriDAS/emu/fast_daq/csc_display/src \
TriDAS/emu/farmer/src/common \
TriDAS/emu/emuDCS/drivers/gbit-vme/eth_hook_jtag_simple \
TriDAS/emu/emuDCS/drivers/gbit-vme/dl2k_driver \
TriDAS/emu/emuDCS/PeripheralXtop/src/common \
TriDAS/emu/emuDCS/PeripheralCore/src/common \
TriDAS/emu/emuDCS/PeripheralApps/xml \
TriDAS/emu/emuDCS/PeripheralApps/test/common \
TriDAS/emu/emuDCS/PeripheralApps/src/common \
TriDAS/emu/emuDCS/PCSwitches/test/common \
TriDAS/emu/emuDCS/PCSwitches/src/common \
TriDAS/emu/emuDCS/OnlineDB/test/common \
TriDAS/emu/emuDCS/OnlineDB/src/common \
TriDAS/emu/emuDCS/FEDUtils/src/common \
TriDAS/emu/emuDCS/FEDCore/src/common \
TriDAS/emu/emuDCS/FEDApps/src/common \
TriDAS/emu/emuDCS/DCFEBCheck/test/linux/x86 \
TriDAS/emu/emuDCS/DCFEBCheck/test/common \
TriDAS/emu/emuDCS/DCFEBCheck/src/linux/x86 \
TriDAS/emu/emuDCS/DCFEBCheck/src/common/new \
TriDAS/emu/emuDCS/DCFEBCheck/src/common \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/inteldual_newkernel/mmaptest2 \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/inteldual_newkernel/mmaptest \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/inteldual_newkernel/eth_hook_jtag_simple \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/inteldual_newkernel/eth_hook_2_nobigphysxxx \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/inteldual_newkernel/e1000-7.0.39/src \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/inteldual/eth_hook_jtag_simple \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/inteldual/eth_hook_2_nobigphysxxx \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/inteldual/e1000-7.0.39/src \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/eth_hook_jtag_simple \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/dl2khook.old/eth_hook_2_nobigphysxxx \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/dl2khook.old/dl2k_driver \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/dl2khook/eth_hook_2_nobigphysxxx \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/dl2khook/dl2k_driver \
TriDAS/emu/emuDCS/DCFEBCheck/drivers/acenic_driver \
TriDAS/emu/drivers/igb_emu/igb-4.1.2/src \
TriDAS/emu/drivers/igb_emu/eth_hook_5_vme \
TriDAS/emu/drivers/igb_emu/eth_hook_5_daq \
TriDAS/emu/drivers/igb_emu/eth_hook_4_vme \
TriDAS/emu/drivers/igb_emu/eth_hook_4_daq \
TriDAS/emu/drivers/igb_emu/eth_hook_3_vme \
TriDAS/emu/drivers/igb_emu/eth_hook_3_daq \
TriDAS/emu/drivers/igb_emu/eth_hook_2_vme \
TriDAS/emu/drivers/igb_emu/eth_hook_2_daq \
TriDAS/emu/drivers/gbit-vme-slc5/eth_hook_jtag_simple \
TriDAS/emu/drivers/gbit-vme-slc5/dl2k_driver \
TriDAS/emu/drivers/gbit-vme/eth_hook_jtag_simple \
TriDAS/emu/drivers/gbit-vme/dl2k_driver \
TriDAS/emu/drivers/e1000hook/mmaptest2 \
TriDAS/emu/drivers/e1000hook/mmaptest \
TriDAS/emu/drivers/e1000hook/eth_hook_jtag_simple \
TriDAS/emu/drivers/e1000hook/eth_hook_5_nobigphysxxx \
TriDAS/emu/drivers/e1000hook/eth_hook_4_nobigphysxxx \
TriDAS/emu/drivers/e1000hook/eth_hook_3_nobigphysxxx \
TriDAS/emu/drivers/e1000hook/eth_hook_2_nobigphysxxx \
TriDAS/emu/drivers/e1000hook/e1000-7.0.39/src \
TriDAS/emu/drivers/e1000_emu/eth_hook_5_vme \
TriDAS/emu/drivers/e1000_emu/eth_hook_5_daq \
TriDAS/emu/drivers/e1000_emu/eth_hook_4_vme \
TriDAS/emu/drivers/e1000_emu/eth_hook_4_daq \
TriDAS/emu/drivers/e1000_emu/eth_hook_3_vme \
TriDAS/emu/drivers/e1000_emu/eth_hook_3_daq \
TriDAS/emu/drivers/e1000_emu/eth_hook_2_vme \
TriDAS/emu/drivers/e1000_emu/eth_hook_2_daq \
TriDAS/emu/drivers/e1000_emu/e1000-7.0.39/src \
TriDAS/emu/drivers/dlk2-daq-pcvme/eth_hook_jtag_simple \
TriDAS/emu/drivers/dlk2-daq-pcvme/eth_hook_3_nobigphysxxx \
TriDAS/emu/drivers/dlk2-daq-pcvme/dl2k_driver \
TriDAS/emu/drivers/dl2khook/eth_hook_2_nobigphysxxx \
TriDAS/emu/drivers/dl2khook/dl2k_driver \
TriDAS/emu/dqm/utils/src/common \
TriDAS/emu/dqm/tfmonitor/src/common \
TriDAS/emu/dqm/tfdisplay/src/common \
TriDAS/emu/dqm/tfanalyzer/test/common \
TriDAS/emu/dqm/tfanalyzer/src/common \
TriDAS/emu/dqm/dbutils/src/common \
TriDAS/emu/dqm/cscmonitor/src/common \
TriDAS/emu/dqm/cscdisplay/src/common \
TriDAS/emu/dqm/cscanalyzer/src/common \
TriDAS/emu/dqm/common/src/common \
TriDAS/emu/dqm/calibration/src/common \
TriDAS/emu/daq/writer/src/common \
TriDAS/emu/daq/ta/src/common \
TriDAS/emu/daq/server/src/common \
TriDAS/emu/daq/rui/src/common \
TriDAS/emu/daq/reader/src/common \
TriDAS/emu/daq/manager/src/common \
TriDAS/emu/daq/fu/src/common \
TriDAS/emu/base/test/common \
TriDAS/emu/base/src/common \
TriDAS/emu/base/src/common/utils \

