#ifndef _FMMTRANSITIONTEST_H
#define _FMMTRANSITIONTEST_H

/**
 *     @class FMMTransitionTest
 *
 *     @short Test the FMM by internally generating test states.
 *
 *            This test uses transitions generated by an tts::FMMTransitionGenerator class.
 *            The following steps are performed:
 * 
 *            @li The transitions are loaded into the internal test inputs of the FMM
 *            @li output of the FMM is checked against an Emulation of the FMM Logic. 
 *            @li The internal func state of the FMM is checked against an emulation of the logic. 
 *            @li After a set of 128k transtitions, the history memory of 
 *                FMM is checked against the series of generated transitions. 
 *
 *       @see ---
 *    @author Hannes Sakulin
 * $Revision: 1.1 $
 *     $Date: 2007/03/27 07:53:27 $
 *
 *
 **/

#include "tts/fmm/FMMBasicTest.hh"
#include "tts/fmm/FMMCard.hh"
#include "tts/fmm/FMMTransitionGenerator.hh"
#include "tts/fmm/FMMConfiguration.hh"

#include <iostream>
#include <stdint.h>

namespace tts {

  class FMMTransitionTest : public tts::FMMBasicTest {
  
  public:
    /// c-tor
    ///
    /// @param card is the FMMCard to use
    /// @param tg is the transition generator to use
    /// @param os is an std::ostream to which output is directed.
    FMMTransitionTest( tts::FMMCard& card, 
		       tts::FMMTransitionGenerator& tg,
		       std::ostream& os = std::cout, 
		       tts::FMMBasicTest::VerbosityLevel vlevel = tts::FMMBasicTest::V_ERR) 
      : tts::FMMBasicTest(os, vlevel), _card(card), _tg(tg), _random(true) {};

    /// d-tor
    virtual ~FMMTransitionTest() {};

    /// set the test configuration 
    ///
    /// @param random is true for random choice of configuration (at the beginning of each loop)
    /// @param cfg is the FMM Configuration to be used if not in random mode (i.e. random=false)
    void setConfiguration(bool random = true, tts::FMMConfiguration cfg = tts::FMMConfiguration()) 
    { _random = random; _cfg=cfg; }; 


    /// get the name
    virtual std::string getName() const { return "FMMTransitionTest"; }; 

    /// get the version of the test
    virtual std::string getVersion() const;

    /// get the parameters of the test
    ///
    /// returns any special parameters of the test as a std::string 
    virtual std::string getParameters() const;

  private:
    /// run the test
    ///
    /// returns true if successful, false if not 
    virtual bool _run(uint32_t nloops);

    tts::FMMConfiguration getRandomConfiguration();

    tts::FMMCard& _card;
    tts::FMMTransitionGenerator& _tg;
    bool _random;

    tts::FMMConfiguration _cfg;
  };

}
#endif
